services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data.db:/app/data.db
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
